### ISSUE TITLE
Crashes in cleanup_tmpdir near the end of a run

### ISSUE THREAD

**Issue by brettcs** [pjotrp/bioruby-vcf#36]
We had a run that started this way:

    bio-vcf 0.9.0 (biogem Ruby 2.1.3 with pcows) by Pjotr Prins 2015
    Options: {:show_help=>false, :source=>"https://github.com/CuppenResearch/bioruby-vcf", :version=>"0.9.0 (Pjotr Prins)", :date=>"2016-02-14 21:36:51 +0000", :thread_lines=>40000, :timeout=>180, :filter=>"rec.sample['24385-12878-30-200'].dp>=20 and rec.sample['24385-200'].dp>=20 and r.info.fb_ssc>=20 and qual>=10", :sfilter=>"s.gq>=15"}

And ended this way:

    Processing /tmp/crunch-job-task-work/compute118.1/bio-vcf_20160214-187-1c2phn1/000002-bio-vcf
    Directory not empty @ dir_s_rmdir - /tmp/crunch-job-task-work/compute118.1/bio-vcf_20160214-187-1c2phn1

After this the program exited nonzero.  It looks like this came from cleanup_tmpdir (the only place in the code that calls Dir.unlink).  This error happens rarely, so it looks like it might be a race condition in the way bio-vcf removes files from the temporary directory.

[This code seems like one place for a race condition may arise](https://github.com/pjotrp/bioruby-vcf/blob/master/lib/bio-vcf/pcows.rb#L122-L129): if the file hasn't been moved to its .keep name within .1 seconds (e.g., because the filesystem is under other load), the code may continue without ever removing it, but it could finally be there by the time cleanup_tmpdir is called.  Perhaps those lines should wait in a loop for the .keep file to appear, and then remove it?  I'm not totally sure of that diagnosis, but the sleep jumped out as a likely candidate to introduce a race condition, at least.

**Comment by pjotrp** [comment]
@brettcs Thanks for finding this. It looks like it needed an extra call to process_output to remove the final output chunk. Please test https://github.com/pjotrp/bioruby-vcf/commit/f03082579070385697448eaddcf0496aedf66eee

**Comment by pjotrp** [comment]
No more complaints.
